version: 2

jobs:
    check-python-cs:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: sudo pip install pycodestyle
            - run:
                  name: Check cs
                  command: pycodestyle --ignore=E501,W605,E722 invoke.py tasks.py

    tests:
        machine:
            docker_layer_caching: false
            image: ubuntu-1604:201903-01
        working_directory: ~/docker-starter
        steps:
            - checkout
            - run:
                name: Install Requirements
                command: |
                    set -e
                    pip install --upgrade pip
                    pip install --user pipenv
                    ~/.local/bin/pipenv install
            - run:
                name: Install everything
                command: |
                    set -e
                    ~/.local/bin/pipenv run inv start
                    sleep 5
            - run:
                name: Unit tests
                command: |
                    set -e
                    set -o pipefail
                    ~/.local/bin/pipenv run inv unitTests
            - run:
                  name: Code quality
                  command: |
                      set -e
                      set -o pipefail
                      ~/.local/bin/pipenv run inv csFixerDry

workflows:
    version: 2
    check_and_tests:
        jobs:
            - check-python-cs
            - tests
