App\Entity\User:
    attributes:
        id:
            groups: ['user_read']
        firstName: &readWrite
            groups: ['user_read', 'user_write']
        lastName:
            <<: *readWrite
        email:
            <<: *readWrite
        roles:
            <<: *readWrite
        token:
            groups: ['user_token']
