api_platform:
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/resources']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            - { name: 'Authorization', type: 'header' }
    path_segment_name_generator: 'api_platform.path_segment_name_generator.dash'
    title: 'Humand API'
