security:
    encoders:
        App\Entity\User:
            algorithm: auto


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        docs:
            pattern:   ^/api/docs
            anonymous: ~

        dictionaries:
            pattern:   ^/api/dictionaries
            anonymous: ~

        token:
            pattern:  ^/api/token
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path:      /api/token
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        forget_password:
            pattern: ^/api/forget-password
            provider: app_user_provider
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - App\Security\Authenticator\EmailAuthenticator

        reset_password:
            pattern: ^/api/reset-password
            provider: app_user_provider
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - App\Security\Authenticator\TokenAuthenticator

        main:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator


            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/forget-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/dictionaries , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
