version: '3.7'

volumes:
    db-data: {}

services:
    router:
        build: services/router
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        network_mode: host

    api:
        build: services/api
        depends_on:
            - db
        volumes:
            - "../../${PROJECT_DIRECTORY}/backend:/home/app/application:cached"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}-api.rule=Host(`api.${PROJECT_ROOT_DOMAIN}`)"
#            - "traefik.http.routers.${PROJECT_NAME}-api.tls=true"
#            - "traefik.http.routers.${PROJECT_NAME}-api-unsecure.rule=Host(`api.${PROJECT_ROOT_DOMAIN}`)"
#            # Comment the next line to be able to access api via HTTP instead of HTTPS
#            - "traefik.http.routers.${PROJECT_NAME}-api-unsecure.middlewares=redirect-to-https@file"

    front:
        # Use a static website hosting service in production
        # See https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment
        build:
            context: ./../../application/front
            dockerfile: ./../../infrastructure/docker/services/front/Dockerfile
        tty: true
        user: '1000'
        volumes:
            - "../../${PROJECT_DIRECTORY}/front:/home/app/application"
            - "/home/app/application/node_modules"
        ports:
            - "3000:3000"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}-front.rule=Host(${PROJECT_DOMAINS})"
#            - "traefik.http.routers.${PROJECT_NAME}-front.tls=true"
#            - "traefik.http.routers.${PROJECT_NAME}-front-unsecure.rule=Host(${PROJECT_DOMAINS})"
            # Comment the next line to be able to access front via HTTP instead of HTTPS
#            - "traefik.http.routers.${PROJECT_NAME}-front-unsecure.middlewares=redirect-to-https@file"

    db:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=humand
            - MYSQL_USER=foo
            - MYSQL_PASSWORD=bar
        volumes:
            - db-data:/var/lib/mysql


    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - PMA_HOST=db
            - PMA_USER=foo
            - PMA_PASSWORD=bar
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}-phpmyadmin.rule=Host(`pma.${PROJECT_ROOT_DOMAIN}`)"

    maildev:
        image: djfarrelly/maildev
        command: ["bin/maildev", "--web", "80", "--smtp", "25", "--hide-extensions", "STARTTLS"]
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}-maildev.rule=Host(`maildev.${PROJECT_ROOT_DOMAIN}`)"
            - "traefik.http.routers.${PROJECT_NAME}-maildev.tls=true"
            - "traefik.http.services.maildev.loadbalancer.server.port=80"
