version: '3.7'

volumes:
    db-data: {}

services:
    router:
        build: services/router
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        network_mode: host

    frontend:
        build: services/frontend
        depends_on:
            - db
        volumes:
            - "../../${PROJECT_DIRECTORY}:/home/app/application:cached"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}-frontend.rule=Host(${PROJECT_DOMAINS})"
            - "traefik.http.routers.${PROJECT_NAME}-frontend.tls=true"
            - "traefik.http.routers.${PROJECT_NAME}-frontend-unsecure.rule=Host(${PROJECT_DOMAINS})"
            # Comment the next line to be able to access frontend via HTTP instead of HTTPS
            - "traefik.http.routers.${PROJECT_NAME}-frontend-unsecure.middlewares=redirect-to-https@file"

    db:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=humand
            - MYSQL_USER=foo
            - MYSQL_PASSWORD=bar
        volumes:
            - db-data:/var/lib/mysql


    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - PMA_HOST=db
            - PMA_USER=foo
            - PMA_PASSWORD=bar
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}-phpmyadmin.rule=Host(`pma.${PROJECT_ROOT_DOMAIN}`)"
