App\Entity\Leave:
    normalization_context:
        groups: ['leave_read']

    itemOperations:
        get: ~
        delete: ~

    collectionOperations:
        get: ~
        post:
            method: POST
            controller: App\Controller\CreateLeavesAction
            normalization_context:
                groups: ['multi_leave']
