App\Entity\User:
    attributes:
        denormalization_context:
            groups: ['user_write']
        normalization_context:
            groups: ['user_read']

    collectionOperations:
        get: ~
        post: ~
        forget_password:
            method: POST
            path: /forget-password
            controller: App\Controller\ForgetPasswordAction
            normalization_context: { groups: [] }
            read: false
        reset_password:
            method: POST
            path: /reset-password/{token}
            controller: App\Controller\ResetPasswordAction
            read: false

    itemOperations: ~
